import discord
from discord.ext import commands

import math


class Fun(commands.Cog):

  def __init__(self, bot):
    self.bot = bot

  @commands.hybrid_command(help='Redirection')
  async def magsqr(self, ctx):

    await ctx.send(
      "Magic Squares are square grids with a special arrangement of numbers in them. These numbers are special because every row, column and diagonal adds up to the same _magic number_ and now you can choose that number! \n\nFor 5x5 magic square use `>magsqr5 [magic number]`\nFor 3x3 magic square use `magsqr3 [magic number]`"
    )

  @commands.hybrid_command(
    help='Makes a 3x3 magic square for a sum of your choice. (Work in progress)'
  )
  async def magsqr3(self, ctx, sum: int):
    #Data
    SMALLSQR = [[7, 0, 5], [2, 4, 6], [3, 8, 1]]  #3x3 sum 12
    #\Data

    desc = f'Magic Squares are square grids with a special arrangement of numbers in them. These numbers are special because every row, column and diagonal adds up to the same _magic number_, here `{sum}`'
    if sum == 69:
      desc = desc + ' Nice...'

    msg = discord.Embed(
      title='3x3 Magic square',
      description=desc,
      color=000000)
    base = int(math.floor((sum - 12) / 3))
    diff = sum - (base * 3) - 12
    digits = len(str(base + 9))
    
    if base < 0:
      msg.add_field(
        name="Note",
        value=
        "I had to use negative integers for this magic square. To avoid it please give repetitive sum above 12."
      )

    for i in range(3):
      for j in range(3):
        SMALLSQR[i][j] += base

    SMALLSQR[0][0] += diff
    SMALLSQR[1][2] += diff
    SMALLSQR[2][1] += diff

    msgstr = ' '
    for row in SMALLSQR:
      for element in row:
        msgstr = msgstr + str(element).zfill(digits) + '  '
      msgstr = msgstr + '\n '
    msgstr = msgstr[:-3]
    msg.add_field(name="Magic Square for Magic Number " + str(sum),
                  value=f'```\n{msgstr}```',
                  inline=False)

    msg.set_footer(
      text="Magic square generated by Amazoo's Code \nrequested by: {}".format(
        ctx.author.display_name))

    await ctx.send(embed=msg)

  @commands.hybrid_command(
    help='Makes a 5x5 magic square for a sum of your choice. (Work in progress)'
  )
  async def magsqr5(self, ctx, sum: int):
    #Data
    BEEGSQR = [[16, 23, 0, 7, 14], [22, 4, 6, 13, 15], [3, 5, 12, 19, 21],
               [9, 11, 18, 20, 2], [10, 17, 24, 1, 8]]  #5x5 sum 60
    #\Data

    desc = f'Magic Squares are square grids with a special arrangement of numbers in them. These numbers are special because every row, column and diagonal adds up to the same _magic number_, here `{sum}`'
    if sum == 69:
      desc = desc + ' Nice...'

    msg = discord.Embed(
      title=f'A 5x5 Magic square with repeating sum as{sum}',
      description=desc,
      color=000000)
    base = int(math.floor((sum - 60) / 5))
    diff = sum - (base * 5) - 60
    digits = len(str(base + 25))

    if base < 0:
      msg.add_field(
        name="Note",
        value=
        "I had to use negative integers for this magic square. To avoid it please give repetitive sum above 60"
      )

    for i in range(5):
      for j in range(5):
        BEEGSQR[i][j] += base

    BEEGSQR[0][0] += diff
    BEEGSQR[1][2] += diff
    BEEGSQR[2][1] += diff

    msgstr = ' '
    for row in BEEGSQR:
      for element in row:
        msgstr = msgstr + str(element).zfill(digits) + '  '
      msgstr = msgstr + '\n '
    msgstr = msgstr[:-2]
    msg.add_field(name="Magic Square for Magic Number " + str(sum),
                  value=f'```\n{msgstr}```',
                  inline=False)

    msg.set_footer(
      text="Magic square generated by Amazoo's Code \nrequested by: {}".format(
        ctx.author.display_name))

    await ctx.send(embed=msg)


async def setup(bot):
  await bot.add_cog(Fun(bot))
